project:
  type: website

website:
  site-url: https://palaeoverse.org
  image: "/images/logo.png"
  favicon: "/images/favicon.png"
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/palaeoverse/palaeoverse-quarto
  page-footer: 
    background: "#c1e0e2"
    left: |
      [Get involved with Palaeoverse](index.qmd#get-involved)  [![](/images/logo.png){fig-alt="Palaeoverse" width=30px}](index.qmd#get-involved)
    center: 
      - href: conduct.qmd
        text: Code of Conduct
    right: 
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/palaeoverse.bsky.social
      - text: "{{< iconify fa6-brands:github >}}"
        href: https://github.com/palaeoverse
      - text: "{{< iconify fa6-brands:youtube >}}"
        href: https://www.youtube.com/@ThePalaeoverse
  navbar:
    pinned: true
    background: "#c1e0e2"
    logo: "/images/logo.png"
    right: 
      - href: index.qmd
        text: 🏠
      - href: index.qmd#our-toolkits
        text: R Packages
      - text: Resources
        menu:
         - href: index.qmd#our-resources
           text: Our Resources
         - href: cheatsheets.qmd
           text: Cheat Sheets
         - href: https://cran.r-project.org/web/views/Paleontology.html
           text: CRAN Task View
         - href: directory.qmd
           text: Directory
         - href: funding.qmd
           text: Grant Track
         - href: external.qmd
           text: External Resources
      - href: index.qmd#community-spaces
        text: Community
      - href: index.qmd#get-involved
        text: Contribute
      - href: index.qmd#about-us
        text: About Us
      - href: lectures.qmd
        text: Lecture Series
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/palaeoverse.bsky.social
      - text: "{{< iconify fa6-brands:github >}}"
        href: https://github.com/palaeoverse
      - text: "{{< iconify fa6-brands:youtube >}}"
        href: https://www.youtube.com/@ThePalaeoverse

format:
  html:
    theme: flatly
    link-external-icon: false
    link-external-newwindow: true
    fontcolor: "#565656"
    linkcolor: "#565656"
    css: styles.css
    toc: true
    toc-depth: 3
    code-block-border-left: false
