project:
  type: website

website:
  site-url: https://palaeoverse.org
  title: "Palaeoverse"
  image: "/images/palaeoverse-pkg.png"
  favicon: "/images/palaeoverse-pkg.png"
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/palaeoverse-community/palaeoverse-quarto
  repo-actions: [edit, issue]
  page-footer: 
    left: |
      Get involved with Palaeoverse [![](/images/palaeoverse-pkg.png){fig-alt="Palaeoverse" width=30px}](./about.qmd#contribute)
    center: 
      - href: about.qmd
        text: About Palaeoverse
      - href: conduct.qmd
        text: Code of Conduct
    right: 
      - icon: github
        href: https://github.com/palaeoverse-community
      - icon: twitter 
        href: https://twitter.com/ThePalaeoverse
  navbar:
    pinned: true
    background: "#1c9099"
    logo: "/images/palaeoverse-pkg.png"
    left: 
      - href: index.qmd
        text: Overview
      - about.qmd
      - href: package.qmd
        text: R Packages
      - href: directory.qmd
        text: Directory
      - href: funding.qmd
        text: Grant Track
      - community.qmd
      - news.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ThePalaeoverse
        aria-label: Palaeoverse Twitter
      - icon: github
        href: https://github.com/palaeoverse-community/palaeoverse-quarto
        aria-label: Palaeoverse GitHub

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: "#1c9099"
    link-external-icon: false
    link-external-newwindow: true
    css: styles.css
    toc: true
    toc-depth: 3
