---
title-block-banner: true
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
toc: false
---

# Palaeoverse Directory {.center-h1}

::: justify
Welcome to the Palaeoverse Directory! This resource is provided to promote the communciation of upcoming conferences, workshops, and vacancies. It also provides a register of research labs and their research focus. We hope that this resource will foster networking and collaboration across the globe.

If you wish to register an upcoming conference, workshop, vacancy or your lab, please complete the <a href="./form/index.qmd" target="_blank">submission form</a>.

Posts shared here do not imply endorsement from the Palaeoverse team and we can hold no responsibility for any interactions you make via this service. If you face any issues or have any concerns about current postings, please contact a member of the Palaeoverse team.

```{r}
#| echo: false
#| warning: false
# Load libraries
library(leaflet)
library(leaflet.extras)
library(dplyr)
library(tidygeocoder)
library(googlesheets4)
# Get sheet
df <- read_sheet("https://docs.google.com/spreadsheets/d/1escqpJM_Ljt5h5claM0xV5e9IEWBv6rNMIsuQsnUXYY/edit?usp=sharing")
# Get addresses
address <- data.frame(name = df$Title,
                      addr = paste(df$Street, df$City, df$Province, df$Country, sep = ", "))
coordinates <- address %>%
  geocode(addr)
df <- bind_cols(df, coordinates)

icons <- awesomeIconList(
  Lab = makeAwesomeIcon(icon = "group",
                        iconColor = "#FFFFFF",
                        library = "fa",
                        markerColor = "cadetblue"),
  Conference = makeAwesomeIcon(icon = "comments", 
                               iconColor = "#FFFFFF",
                               library = "fa",
                               markerColor = "darkred"),
  Workshop = makeAwesomeIcon(icon = "gear",
                             iconColor = "#FFFFFF",
                             library = "fa",
                             markerColor = "orange"),
  Vacancy = makeAwesomeIcon(icon = "briefcase",
                            iconColor = "#FFFFFF",
                            library = "fa",
                            markerColor = "darkpurple")
)

m <- leaflet(df) %>% 
  setView(lng = 0,
          lat = 0,
          zoom = 1) %>% 
  addProviderTiles(providers$CartoDB.Positron,
                   options = providerTileOptions(minZoom = 1, maxZoom = 20)) %>%
  addAwesomeMarkers(lng = ~long,
             lat = ~lat,
             icon = ~icons[Post],
             group = c("posts"),
             label = paste0(df$Post, ": ", df$Title, ", ", df$Institution),
             popup = ~paste("<b>",
                            Title,
                            "</b>",
                            "<br>",
                            Description,
                            "<br>",
                            "<a href='mailto:",
                            Email,
                            "'>Contact</a>",
                            "|",
                            "<a href='",
                            Link,
                            "'>More info</a>"),
             clusterOptions = markerClusterOptions()) %>%
  addLayersControl(
    overlayGroups = ~Post,
    options = layersControlOptions(collapsed = FALSE)) %>%
  addResetMapButton() %>%
  addSearchFeatures(
    targetGroups = c("posts"),
    options = searchFeaturesOptions(
      zoom = 12, openPopup = TRUE, firstTipSubmit = TRUE,
      autoCollapse = TRUE, hideMarkerOnCollapse = TRUE )) %>%
  addFullscreenControl()
m
```
:::

# Recent announcements {.center-h1}
