---
pagetitle: Lectures
title: Lecture Series
title-block-banner: true
toc: true
page-layout: custom
---

::: {.grid .white-background}

::: {.g-col-3}

:::

::: {.g-col-6 .center}

::: {.huge}
**Summer 2025**

:::

::: {.justify}

We are excited to announce the Summer 2025 Palaeoverse Lecture Series focused on software development and methodological approaches in palaeontology. The aim of this lecture series is to promote the use of new tools in the field and to give researchers a platform to showcase their work. The format is intended to be flexible but will generally include a short seminar followed by a demonstration of the speaker's software toolkit and/or method and will conclude with a group discussion.

**Lectures will be held on the last Thursday of each month from 15:00--16:00 UTC\*.**

This semester, we will be joined by the following four speakers:

**June 26^th^ 2025 - Dr Katie Collins, Natural History Museum (UK)**  
Both round and upward: Spiral morphometry and how to compare things that are the same, but different 

**July 31^st^ 2025 - Summer break, no lecture**

**August 28^th^ 2025 - Amy Shipley, University of Leeds**  
Modelling ancient food webs: ecosystem changes across the Pliocene marine megafaunal extinction

**September 25^th^ 2025 - Dr Nicolás Mongiardino Koch, University of California San Diego and Dr Russell Garwood, University of Manchester**  
The Tree of Life and Death: What do Fossil Taxa Contribute to Morphological Phylogenetics? 

Please register below for the series. All are welcome to join and we ask that all participants abide by the [**Palaeoverse Code of Conduct**](conduct.qmd).

:::

<a href="https://bit.ly/palaeoverse-lecture-series-2025" class="card-link h2">🚨**REGISTER**🚨</a>

::: {.huge}
**Previous lectures**
:::

**May 29^th^ 2025 - Dr Allison Hsiang, Stockholm University**  
Automating large-scale morphometric data generation using AutoMorph and deep learning 

<iframe width="560" height="315" src="https://www.youtube.com/embed/isavzYBoyPU?si=fAw1sXnhyXDLQv8_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**April 24^th^ 2025 - Dr Richard Stockey, University of Southampton**  
Modelling ancient animal habitats in space and time: linking fossils and Earth system models

<iframe width="560" height="315" src="https://www.youtube.com/embed/o5VZg2hqtA0?si=PbY6Vk8r3js_7Qqk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**March 27^th^ 2025 - Dr Ond&rcaron;ej Mottl - Charles University**  
FOSSILPOL: The Workflow To Process Global Palaeoecological Data Of Fossil Pollen For Vegetation-Based Macroecological Synthesis  

<iframe width="560" height="315" src="https://www.youtube.com/embed/u-N_yI2Ws9o?si=q2eugDxJNqKib9m2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**February 27^th^ 2025 - Dr Xia Wang, Chengdu University of Technology**  
DDE-Outcrop3D: an interactive platform for digital outcrop models  

<iframe width="560" height="315" src="https://www.youtube.com/embed/UZQSMHtsLC0?si=GnSD1PMPbisVd8Za" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**January 30^th^ 2025 - Dr Ádám Kocsis, FAU Erlangen-Nürnberg**  
The 'rgplates' interface to tectonic calculations in R: overview, updates and related projects  
[Lecture materials](https://github.com/adamkocsis/rgplates_palaeoverse)

<iframe width="560" height="315" src="https://www.youtube.com/embed/vrezsXEknoY?si=dOaTwQ3tQRMTUrS1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**December 19^th^ 2024 - Dr Thomas Guillerme, University of Sheffield**  
Top 10 of the best disparity metrics to use in palaeobiology; number 10 might surprise you!  
Lecture materials: [Vignette](https://cdn.githubraw.com/TGuillerme/dispRity/refs/heads/master/inst/vignettes/select_disparity_metrics.html) | [Code](https://github.com/TGuillerme/dispRity/blob/master/inst/vignettes/select_disparity_metrics.Rmd)

<iframe width="560" height="315" src="https://www.youtube.com/embed/JKpUQbxID9A?si=izjfyfEn_7TSHclD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**November 21^st^ 2024 - Dr Roxanne Banker, Providence College**  
Quantitative approaches to understanding marine ecosystems: Insights from Stellar's Sea Cow and ancient food webs

<iframe width="560" height="315" src="https://www.youtube.com/embed/jL4z3dqSxvk?si=wpOVTHKcrsP1l0wh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**October 31^st^ 2024 - Niklas Hohmann, Utrecht University**  
Building modeling pipelines for stratigraphic paleobiology in R  
Lecture materials: [https://doi.org/10.5281/zenodo.14001502](https://doi.org/10.5281/zenodo.14001502)

<iframe width="560" height="315" src="https://www.youtube.com/embed/1H-xnD82fzA?si=zuqFdJ5vnFcOlsav" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**September 26^th^ 2024 - Dr Euan Furness, University of Cambridge**  
Reproducing emergent eco-evolutionary patterns from a first-principles agent-based model

<iframe width="560" height="315" src="https://www.youtube.com/embed/UMQZfIUJzTA?si=ujUsK38RtaF-kCQA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**August 29^th^ 2024 - Dr Rafaela Missagia, Universidade de São Paulo**  
Advancing morphological research with computed tomography: a case study on predatory rodents

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZeSkob8wtfE?si=cXOMi_9KVX0c86Dw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**July 25^th^ 2024 - Dr Gawain Antell, University of California**  
Spatially standardized subsampling for fair comparisons and meaningful characterisations of ecological metrics through time

At the request of the speaker, this lecture is not publicly available. However, you may request a private link to the talk from either [Dr Gawain Antell](mailto:antell@geog.ucla.edu) or [Dr Erin Dillon](mailto:DillonE@si.edu).

**June 27^th^ 2024 - Dr April Wright, Southeastern Louisiana University**  
Models, Meaning, and the Middle Cambrian

<iframe width="560" height="315" src="https://www.youtube.com/embed/hA2ETW7R5Jo?si=n3X9A-EjwF7AgiAd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**May 30^th^ 2024 - Prof. Daniele Silvestro, University of Fribourg**  
Neural network models to infer diversity trajectories and the drivers of speciation and extinction

<iframe width="560" height="315" src="https://www.youtube.com/embed/hGJ7OMiWpy4?si=AMsxjTF6LA8o0Gd3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**April 25^th^ 2024 - Laura Mulvey, FAU Erlangen-Nürnberg**  
Assessing the adequacy of morphological models used in palaeobiology

<iframe width="560" height="315" src="https://www.youtube.com/embed/7S7rsUmd2Sk?si=Ar7SPPGTfr1YSNUk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**March 28^th^ 2024 - Dr Benjamin Shipley, University of Oxford**  
Modelling species range shifts in the past and future

<iframe width="560" height="315" src="https://www.youtube.com/embed/ScnBfUYNScU?si=ieKVO2UC5M7zfxik" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**February 29^th^ 2024 - Dr Emily Mitchell, University of Cambridge**  
Using Spatial point process analyses to quantify the behavioural ecology behind trace fossils

<iframe width="560" height="315" src="https://www.youtube.com/embed/cW3Glw_zN0I?si=SBvAlltr6Yr5v-ZG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:::

::: {.g-col-3}

:::

:::