---
title: Grant Track Form
title-block-banner: true
toc: false
---

::: justify
This service is provided to contribute to the **Grant Track** community database of research funding schemes and grants for Palaeobiologists. If you wish to make an entry, please complete the following form. **Please note that all information provided here will be published online and accessible to all.** We aim to update entries once a week.

We reserve the right to refuse the entries of any inappropriate material or remove content where necessary. If you face any issues, please contact <a href="mailto:kilian.eichenseer@gmail.com" style="text-decoration: none" target="_blank">**Kilian Eichenseer**</a> or <a href="mailto:LewisA.Jones@outlook.com" style="text-decoration: none" target="_blank">**Lewis A. Jones**</a>.
:::

------------------------------------------------------------------------

<form name="grant" method="POST" data-netlify="true" onSubmit="submit">

<p>**Name of the grant**</p>

<input name="Name" type="text" placeholder="Name of the grant" required>\
<br>

<p>**Funding body**</p>

<input name="Funder" type="text" placeholder="Funding body" required>\
<br>

<p>**Applicant nationality eligibility (e.g. EU-citizens only)**</p>

<input name="Applicant" type="text" placeholder="Nationality eligibility" required>\
<br>

<p>**Host country**</p>

<input name="Host" type="text" placeholder="Host country" required>\
<br>

<p>**Career stage eligibility**</p>

<input name="Career" type="text" placeholder="Career stage" required>\
<br>

<p>**Grant link**</p>

<input name="URL" type="text" placeholder="URL to further details" required>\
<br>

<p>**Award**</p>

<input name="Award" type="text" placeholder="Value of the grant" required>\
<br>

<p>**Research cost allowance**</p>

<input name="Research" type="text" placeholder="Research cost allowance" required>\
<br>

<p>**Duration**</p>

<input name="Duration" type="text" placeholder="Duration" required>\
<br>

<p>**Application deadline**</p>

<input name="Deadline" type="text" placeholder="Application deadline" required>\
<br>

<button type="submit">Submit</button>

</form>
